import { useEffect } from 'react';
import Head from 'next/head';
import Homepage from '../components/Homepage';
import { useAuth } from '../context/AuthContext';
import Router from 'next/router';


export default function Home() {
  const { currentUser } = useAuth();

  useEffect(() => {
    if (currentUser) {
      Router.push('/journal');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Homepage/>
      </main>
    </>
  )
}
